name: Generate D3 Snake from your contribution graph

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@master
        with:
          github_user_name: truthdeal
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit and push if it's changed
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Update Github Metrics"
          git push
